
  name: CI/CD Pipeline
  
  on:
    push:
      branches:
        - master
  
  jobs:
    build:
      runs-on: ubuntu-latest
  
      steps:
      - name: Checkout the code
        uses: actions/checkout@v3
  
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
  
      - name: Log in to Docker registry
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login https://localhost:443 -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
  
      - name: Build Docker image
        run: |
          docker build -t localhost:443/my-flask-app:latest ./flask_app
  
      - name: Push Docker image to registry
        run: |
          docker push localhost:443/my-flask-app:latest
  